# Generated by Django 2.0.6 on 2018-07-01 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('picture', models.ImageField(upload_to='people')),
                ('gender', models.CharField(max_length=20)),
                ('pronouns', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'permissions': (('can_view_others', 'Can view other people'), ('can_list_others', 'Can list other people'), ('can_edit_profile', 'Can edit / view their profile')),
            },
        ),
    ]
