# Generated by Django 2.0.6 on 2018-06-22 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('picture', models.ImageField(upload_to='people')),
                ('gender', models.CharField(max_length=20)),
                ('pronouns', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'permissions': (('people.can_view_others', 'Can view other people'), ('people.can_list_others', 'Can list other people')),
            },
        ),
    ]
